version: '3.8'

services:
  gateway-nginx:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "10610:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my-frontend
      - my-backend
    networks:
      - app-network

  my-frontend:
    platform: linux/amd64
    build: ./frontend       
    container_name: ft-frontend
    networks:
      - app-network

  my-backend:
    platform: linux/amd64
    build: ./backend        
    container_name: ft-backend
    
    env_file:
      - ./backend/.env
      
    networks:
      - app-network

networks:
  app-network: