FROM node:20-alpine AS builder
RUN npm run build
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
RUN sed -i 's/listen       80;/listen       10611;/' /etc/nginx/conf.d/default.conf
RUN sed -i '/server_name  localhost;/a \    server_tokens off;' /etc/nginx/conf.d/default.conf
EXPOSE 10611
CMD ["nginx", "-g", "daemon off;"]