server {
    listen 80;
    server_tokens off;

    # 1. Frontend
    location / {
        # 👇 แก้เลขตรงนี้ให้เป็น 10610 (ให้ตรงกับ frontend/Dockerfile)
        proxy_pass http://my-frontend:10610; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Backend (เพิ่มส่วนนี้เข้าไป!)
    location /api/ {
        # ถ้าโค้ด Backend คุณเป็น /api/users อยู่แล้ว ไม่ต้องใส่ rewrite
        # แต่ถ้าโค้ดเป็น /users เฉยๆ ให้เปิดบรรทัด rewrite ข้างล่างนี้
        # rewrite ^/api/(.*) /$1 break; 

        proxy_pass http://my-backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}